// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm0FDaNw8nOkXDHQuC9HKl01ZUtPSsBQg',
    appId: '1:106637930808:web:9974be84e3af08938091cd',
    messagingSenderId: '106637930808',
    projectId: 'in-demand-delivery-app',
    authDomain: 'in-demand-delivery-app.firebaseapp.com',
    storageBucket: 'in-demand-delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSib_n2w85g7MGTbjyu2r-ehkebk-v1bc',
    appId: '1:106637930808:android:1bb1749da87d0de58091cd',
    messagingSenderId: '106637930808',
    projectId: 'in-demand-delivery-app',
    storageBucket: 'in-demand-delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCz9h3tZ7YaxJP-S2EZGVhuj6W5gaA1q4',
    appId: '1:106637930808:ios:8140fa719a8e4baa8091cd',
    messagingSenderId: '106637930808',
    projectId: 'in-demand-delivery-app',
    storageBucket: 'in-demand-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.customerDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCz9h3tZ7YaxJP-S2EZGVhuj6W5gaA1q4',
    appId: '1:106637930808:ios:8140fa719a8e4baa8091cd',
    messagingSenderId: '106637930808',
    projectId: 'in-demand-delivery-app',
    storageBucket: 'in-demand-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.customerDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm0FDaNw8nOkXDHQuC9HKl01ZUtPSsBQg',
    appId: '1:106637930808:web:6038cf5a0d2ccef88091cd',
    messagingSenderId: '106637930808',
    projectId: 'in-demand-delivery-app',
    authDomain: 'in-demand-delivery-app.firebaseapp.com',
    storageBucket: 'in-demand-delivery-app.firebasestorage.app',
  );
}
